#! /bin/bash
#
#$Author: ee364f12 $
#$Date: 2016-01-13 10:46:58 -0500 (Wed, 13 Jan 2016) $
#$HeadURL: svn+ssh://ece364sv@ecegrid-thin1/home/ecegrid/a/ece364sv/svn/S16/students/ee364f12/Lab00/Script1 $
#$Revision: 84485 $
Num_of_Param=$#
Param_Values=$@
echo "The Porgram received $Num_of_Param parameters"
echo "The parameters are : "
echo "$Param_Values"
echo "The 2nd parameter is \"$2\""
echo "The 4th parameter is \"$4\""
exit 0
