#! /bin/bash
#
#$Author: ee364f12 $
#$Date: 2016-01-13 10:53:26 -0500 (Wed, 13 Jan 2016) $
#$HeadURL: svn+ssh://ece364sv@ecegrid-thin1/home/ecegrid/a/ece364sv/svn/S16/students/ee364f12/Lab00/Script2 $
#$Revision: 84491 $
for(( n=$1;n>=0;n--))
do
    echo $n
done
